name = "cf-o11y-worker"
main = "build/worker/shim.mjs"
# See https://developers.cloudflare.com/workers/configuration/compatibility-dates/#compatibility-flags for latest
compatibility_date = "2024-04-29"

[triggers]
# Run every minute
crons = ["* * * * *"]

[build]
command = "cargo install -q worker-build && worker-build --release"

[env.dev]
build = { command = "cargo install -q worker-build && worker-build --dev" }

[env.dev.vars]
METRICS_URL = "http://collector:4318/v1/metrics"
CLOUDFLARE_API_URL = "https://api.cloudflare.com/client/v4/graphql"
CLOUDFLARE_API_KEY = "fake"
CLOUDFLARE_ACCOUNT_ID = "1234"
